name: Sync Files to Modules
on: 
  repository_dispatch:
    types:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: test
       run: |
         echo ${{github.repository_owner}}
         echo ${{ github.event.sender.login }}
        